version: '3.9'
services:
  frontend:
    build: ./front-end
    restart: 'always'
    ports:
      - 3000:3000
  backend:
    build: ./back-end
    restart: 'unless-stopped'
    ports:
      - 3001:3001